// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9LukiMkbq8wh6-HxY_sgX2KhcGlO83OM',
    appId: '1:455173426400:web:d44419cd4f34ffb0729485',
    messagingSenderId: '455173426400',
    projectId: 'authtutorial-f147d',
    authDomain: 'authtutorial-f147d.firebaseapp.com',
    storageBucket: 'authtutorial-f147d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvGLrQIXuGd_a1X4y1v7Roptglgx1Uj70',
    appId: '1:455173426400:android:64304585501f63fd729485',
    messagingSenderId: '455173426400',
    projectId: 'authtutorial-f147d',
    storageBucket: 'authtutorial-f147d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcANaC3BVuif2vnjB-x9_UItapLW3GT1I',
    appId: '1:455173426400:ios:6ff8a0a6caa69fe4729485',
    messagingSenderId: '455173426400',
    projectId: 'authtutorial-f147d',
    storageBucket: 'authtutorial-f147d.appspot.com',
    iosClientId: '455173426400-mdvubl9of6fv1hfv7i61vu21of26bmv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcANaC3BVuif2vnjB-x9_UItapLW3GT1I',
    appId: '1:455173426400:ios:6ff8a0a6caa69fe4729485',
    messagingSenderId: '455173426400',
    projectId: 'authtutorial-f147d',
    storageBucket: 'authtutorial-f147d.appspot.com',
    iosClientId: '455173426400-mdvubl9of6fv1hfv7i61vu21of26bmv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicAuth',
  );
}
